# @name login
POST http://www.mumstudents.org/api/login HTTP/1.1
content-type: application/json

{
    "username": "mwp", 
    "password":"123"
}
@token = {{login.response.body.token}}

###

GET  http://www.mumstudents.org/api/animation HTTP/1.1
Authorization: Bearer {{token}}