# @name login
POST https://cs445-project.herokuapp.com/api/login HTTP/1.1
content-type: application/json

{
    "username": "map", 
    "password": "123456"
}
###
@token = {{login.response.body.token}}
###

GET  https://cs445-project.herokuapp.com/api/animation HTTP/1.1
Authorization: Bearer {{token}}